### ISSUE TITLE
Intermittent build failures

### ISSUE THREAD

**Issue by cjyabraham** [linuxfoundation/lfevents#748]
We're still occasionally getting the build failures shown here. We never get them on CNCF. I wonder if you could update all the theme build scripts, libraries, etc. to see if it's a matter of getting on to the latest versions of things.

<img width="1127" alt="Screen Shot 2023-03-09 at 1 18 03 PM" src="https://user-images.githubusercontent.com/463160/224162431-022b70ef-e9c8-481a-9d8c-a02415d7a32a.png">

**Comment by thetwopct** [comment]
From Slack in June 22:

> I don't think it's to do with memory even though that message implies it. I see that message locally sometimes. It started when I updated some of the packages. Some are out of date but because of FoundationPress we can't upgrade fully and there's some dependency issues.

**Comment by thetwopct** [comment]
We have moved to GitHub workflows, and I have [updated the packages](https://github.com/linuxfoundation/lfevents/pull/923) so don't think this should happen again. Lets close for now.
