### ISSUE TITLE
Implement Redis

### ISSUE THREAD

**Issue by thetwopct** [linuxfoundation/lfevents#752]
Let's test Redis out

[Setup guide](https://docs.pantheon.io/guides/object-cache/enable-object-cache)
1. Add to composer.json - "wpackagist-plugin/wp-redis": "^1.3.4"
2. Add the files as instructed
3. Use snippets maybe? https://github.com/pantheon-systems/wp-redis/wiki

**Comment by cjyabraham** [comment]
I don't see a need for this and am put off by the complexity of having another layer of cacheing to worry about. At best, Redis will only have an affect on logged in users and, currently, I think their performance experience is adequate. If we're interested in speeding up db performance, I think it'd be better to focus our efforts on reducing all the hits we get from hacker bots. #749 is a good start on this.

**Comment by thetwopct** [comment]
> I don't see a need for this and am put off by the complexity of having another layer of cacheing to worry about.
