### ISSUE TITLE
New styling for LFEvents newsletter forms

### ISSUE THREAD

**Issue by cjyabraham** [linuxfoundation/lfevents#918]
Newsletter forms are going to have a Country dropdown added to them. Could we get a styling treatment for this field? 

To develop these new styles, you could temporarily add a Country dropdown (ID = form_country) to a form and play around with the styling.

**Comment by cjyabraham** [comment]
@thetwopct any idea how to make the placeholder text "Select Country" grey like the other inputs:
![Screenshot 2024-06-25 at 4 34 14 PM](https://github.com/linuxfoundation/lfevents/assets/463160/ae96da54-448b-4982-8100-7c2fa78a954b)

**Comment by thetwopct** [comment]
You could try

```
option:disabled {
 color: darkgray
}
```

might need specificity:

```
select option:disabled {
 color: darkgray
}
```

**Comment by cjyabraham** [comment]
Some ideas for improvement on [the event's newsletter form](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/):
- make it wrap better at mid-range widths, so instead of going from 4 fields-across directly to 1-across, have it go to 2-across, similar to the homepage newsletter form
- figure out if there's a way to make the placeholder text grey
- reduce the width of the email field relative to the others, similar to how done on homepage
- change placeholder text to "Select country" instead of "Select Country" (task for me)

**Comment by cjyabraham** [comment]
deployed
