### ISSUE TITLE
Remove hardcoded LMFP URL from wp-config.php

### ISSUE THREAD

**Issue by thetwopct** [linuxfoundation/lfevents#934]
We currently have this in wp-config.php

```
define( 'LOAD_MEDIA_FROM_PRODUCTION_URL', 'https://events.linuxfoundation.org/' ); // Sets url for loading media files on dev instance.
```

This makes it difficult/impossible to test locally when you want to sync images from a PR instance instead of the main site. 

Suggest the constant is removed. 

If it needs to be added somewhere (although I don't see where this is useful apart from local development, where it should be down to the developer to apply it or not) a WP CLI command can be added to deployment process, composer install, or lando setup.

```
wp load-media-from-production set "https://production-url.com"
```

or worse case setting the option directly

```
wp option update lmfp_production_url "https://new-production-url.com"
```

**Comment by cjyabraham** [comment]
Noting here that the constant can also be set in the LMFP settings page: https://lfeventsci.lndo.site/wp/wp-admin/options-general.php?page=load-media-from-production

**Comment by cjyabraham** [comment]
Deployed
