### ISSUE TITLE
npm run dev no longer watches for changes

### ISSUE THREAD

**Issue by thetwopct** [linuxfoundation/lfevents#935]
We no longer use browsersync (as it doesnt seem to work properly within lando) but I think the removal of it affected watching files for changes and automatically rebuilding.

When running npm run dev, the build happens but then requires the command to be run again

![Screenshot-2024-08-21 --16 05 52](https://github.com/user-attachments/assets/58d9000e-e591-48d8-a96c-c7bc1a728f71)

**Comment by cjyabraham** [comment]
Deployed
