### ISSUE TITLE
Flying Scripts + speed review

### ISSUE THREAD

**Issue by thetwopct** [linuxfoundation/lfevents#960]
Current:

```
recaptcha
collectedforms.js
js.hs-banner.com
js.hs-analytics.net
livestream
js.hs-scripts.com
v2.js
osano
boomerang
gtag
gtm
```

![Screenshot-2024-12-20 --12 16 12@2x](https://github.com/user-attachments/assets/dfdc25ee-17b8-4292-a3ba-7cab96c3502f)

**Comment by thetwopct** [comment]
I updated the list inline with CNCF (i.e. removed specific sub-domains, generic v2 etc etc)

```
facebook.net
gtag
gtm
hs-analytics.net
hs-banner.com
hs-scripts.com
hscollectedforms.net
hsforms.net
hsleadflows.net
hubspot.com
licdn.com
osano
recaptcha
usemessages.com
```

Pagespeed Insights seems to be ignoring Flying Scripts or possibly mimicking user interaction as the score remains low. A few others have reported this but they put the blame on Flying Scripts - https://wordpress.org/support/topic/the-plugin-sometimes-doesnt-work-on-mobile/ 

I think it's Pagespeed Insights, as Webpagetest.org doesn't see the initial scripts loading.

![Screenshot-2024-12-20 --12 54 38](https://github.com/user-attachments/assets/b9cbc895-6e46-449f-b4c0-ce65ebe06911)

**Comment by thetwopct** [comment]
Consolidate preconnects: https://github.com/linuxfoundation/lfevents/pull/959 

Optimise manifest.file: https://github.com/linuxfoundation/lfevents/pull/961

Q: Should we be including Tag Manager directly if this is managed by Osano? See `lfe-functions` > `lfe_insert_google_tag_manager_head()`

**Comment by thetwopct** [comment]
> Pagespeed Insights seems to be ignoring Flying Scripts or possibly mimicking user interaction as the score remains low. A few others have reported this but they put the blame on Flying Scripts - https://wordpress.org/support/topic/the-plugin-sometimes-doesnt-work-on-mobile/

Ah I think Flying Scripts may have addressed this in a recent update, so going to include plugin upgrades in my PR

![Screenshot-2024-12-20 --21 30 27@2x](https://github.com/user-attachments/assets/4847f50d-8715-4f67-9497-f784d28aae48)

**Comment by thetwopct** [comment]
The update got it. 

![Screenshot-2024-12-20 --21 54 05@2x](https://github.com/user-attachments/assets/48f7d91d-70d1-4b53-9464-fbb1631ddda0)

**Comment by cjyabraham** [comment]
> Q: Should we be including Tag Manager directly if this is managed by Osano? See `lfe-functions` > `lfe_insert_google_tag_manager_head()`

I'm not sure I understand this question. Is there an alternate way of including it?
